### ISSUE TITLE
Do not work with libnotify 0.8

### ISSUE THREAD

**Issue by flroux** [buzz/twitch-indicator#14]
On Arch Linux with libnotify 0.8.0 and twitch-indicator 1.3:

```
Traceback (most recent call last):
  File "/usr/bin/twitch-indicator", line 33, in <module>
    sys.exit(load_entry_point('twitch-indicator==1.3', 'gui_scripts', 'twitch-indicator')())
  File "/usr/bin/twitch-indicator", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/twitch_indicator/__main__.py", line 6, in <module>
    gi.require_version("Notify", "0.7")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Notify not available for version 0.7
```

**Comment by buzz** [comment]
Fixed in 4ee89469870a33ca77dec4873dd18855e031b527
